global:
    scrape_interval: 5s

scrape_configs:
    - job_name: meridian
      static_configs:
          - targets:
                - node-1:9080
                - node-2:9080
                - node-3:9080
